### ISSUE TITLE
missing some X11 deps..?

### ISSUE THREAD

**Issue by dirad** [ChrisTitusTech/dwm-titus#13]
On Debian 11 testing, 
After installing libx11-dev,  running make clean install
I get this error:

```
~/dwm-titus (main) [2]> make clean install
rm -f dwm drw.o dwm.o util.o dwm-6.3.tar.gz
dwm build options:
CFLAGS   = -std=c99 -pedantic -Wall -Wno-deprecated-declarations -Os -I/usr/X11R6/include -I/usr/include/freetype2 -D_DEFAULT_SOURCE -D_BSD_SOURCE -D_POSIX_C_SOURCE=200809L -DVERSION="6.3" -DXINERAMA
LDFLAGS  = -L/usr/X11R6/lib -lX11 -lXinerama -lfontconfig -lXft -lX11-xcb -lxcb -lxcb-res 
CC       = cc
cc -c -std=c99 -pedantic -Wall -Wno-deprecated-declarations -Os -I/usr/X11R6/include -I/usr/include/freetype2 -D_DEFAULT_SOURCE -D_BSD_SOURCE -D_POSIX_C_SOURCE=200809L -DVERSION=\"6.3\" -DXINERAMA drw.c
drw.c:6:10: fatal error: X11/Xft/Xft.h: No such file or directory
    6 | #include <X11/Xft/Xft.h>
      |          ^~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:18: drw.o] Error 1

```

The config file is as default.  
Also tried changing to another directory from /usr/local/ for the prefix and still get the same error.

Update:  changed the location to X11 as
```
X11INC = /usr/include/X11
X11LIB = /usr/lib/x86_64-linux-gnu
```

Still getting that same error

**Comment by ProMaster-4** [comment]
have you got libxft?

**Comment by ProMaster-4** [comment]
`> drw.c:6:10: fatal error: X11/Xft/Xft.h: No such file or directory`

have you got libxft-dev?

**Comment by Aman1337g** [comment]
I am currently using pop-os, I also got the same issue during installation. For me it was resolved after installing the following packages:

`sudo apt install libxft-dev libimlib2-dev libxinerama-dev libxcb1-dev libxcb-res0-dev libxcb-util0-dev libxcb-ewmh-dev`

**Comment by dirad** [comment]
> `> drw.c:6:10: fatal error: X11/Xft/Xft.h: No such file or directory`
> 
> have you got libxft-dev?...

sure do.



> I am currently using pop-os, I also got the same issue during installation. For me it was resolved after installing the following packages:
> 
> `sudo apt install libxft-dev libimlib2-dev libxinerama-dev libxcb1-dev libxcb-res0-dev libxcb-util0-dev libxcb-ewmh-dev`

after this i still baffeled by   

```
 11:31 ❯ make clean install
rm -f dwm drw.o dwm.o util.o dwm-6.5.tar.gz
cc -c -march=native -mtune=native -flto=auto -O3 -std=c99 -pedantic -Wall -Wno-unused-function -Wno-deprecated-declarations -I/usr/include/X11 -I/usr/include/freetype2 -D_DEFAULT_SOURCE -D_BSD_SOURCE -D_XOPEN_SOURCE=700L -DVERSION=\"6.5\" -DXINERAMA drw.c
cc -c -march=native -mtune=native -flto=auto -O3 -std=c99 -pedantic -Wall -Wno-unused-function -Wno-deprecated-declarations -I/usr/include/X11 -I/usr/include/freetype2 -D_DEFAULT_SOURCE -D_BSD_SOURCE -D_XOPEN_SOURCE=700L -DVERSION=\"6.5\" -DXINERAMA dwm.c
dwm.c:47:10: fatal error: X11/Xlib-xcb.h: No such file or directory
   47 | #include <X11/Xlib-xcb.h>
      |          ^~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:12: dwm.o] Error 1
```

**Comment by dirad** [comment]
was missing `libx11-xcb-dev` .

But i dont know if all the other packages i installed on the way were needed. =]

**Comment by Dhyfer1** [comment]
<details>
 <summary>bla bla bla</summary>
 - alwayscenter
-1
-2
-3
-4
</details>
