### ISSUE TITLE
[QUESTION] Prerequisites

### ISSUE THREAD

**Issue by Querzion** [ChrisTitusTech/dwm-titus#32]
Since this is only as I suppose the DWM configurations, what is needed as prerequisites to have it run as it does for you?

**Comment by Querzion** [comment]
Do I use ArchTitus install first and then DWM?

**Comment by Querzion** [comment]
I got an error while compiling, couldn't get it running.

**Comment by RazoBeckett** [comment]
@Querzion close the issue as it's being fixed in #35
