### ISSUE TITLE
NixOS install

### ISSUE THREAD

**Issue by QuantumriderAGI** [ChrisTitusTech/dwm-titus#41]
Got inspired by your video when you installed DWM on NixOS.

Could you please show me what I need to put into my configuration.nix to get it working in NixOS?

**Comment by RazoBeckett** [comment]
```nix
  services.xserver.windowManager.dwm = {
    enable = true;
    package = pkgs.dwm.overrideAttrs {
      src = pkgs.fetchFromGitHub {
        owner = "christitustech";
        repo = "dwm-titus";
        rev = "main";
        sha256 = "sha256-jC1TYDMEzrB0qLc0K8AOcGsep9T2l3sJSja0BuvgkZ0=";
      };
      buildInputs = with pkgs; [
        imlib2Full
        xorg.libX11
        xorg.libX11.dev
        xorg.libXft
        xorg.libXinerama
        xorg.libXrender
        xorg.libxcb
        fontconfig
        gnumake
        gcc
      ];
    };
  };
```

**Comment by RazoBeckett** [comment]
You will still run into issues where copying the dwm.desktop file happens, as Nix will not allow that. I suggest cloning the repo, changing the src to the path of the clone, and removing the following two lines from the Makefile:

```make
mkdir -p /usr/share/xsessions/
test -f /usr/share/xsessions/dwm.desktop || install -Dm644 dwm.desktop /usr/share/xsessions/
```

Then try rebuilding. It will work.

**Comment by QuantumriderAGI** [comment]
Thank you! will give of a shot later today and report

**Comment by RazoBeckett** [comment]
@QuantumriderAGI close this issue if you got dwm working on your NixOS system, thanks ...
