### ISSUE TITLE
DWM Titus refuses to load

### ISSUE THREAD

**Issue by michaeldun123** [ChrisTitusTech/dwm-titus#62]
![image](https://github.com/user-attachments/assets/6de84854-e7e6-4ec6-9dfa-58e2ed053383)

I try and open up dwmtitus from my login manager (SDDM) and it just refuses to load as per the screenshot above

**Comment by RazoBeckett** [comment]
@michaeldun123 oh my boy it's loaded you can see the dwm bar on the top, as sddm doesn't just copies the background of it to the desktop the whole screen panel's screenshot is getting set as your wallpaper, install alacritty and do `MODKEY + X` to launch the terminal.
