### ISSUE TITLE
DWM-TITUS does not build on arch, debian, or rocky linux for me

### ISSUE THREAD

**Issue by jsteinbraker** [ChrisTitusTech/dwm-titus#63]
No matter what i do like you showed a few videos ago @ChrisTitusTech I can't get dwm-titus to build on any distro yes i even tried arch. But on another note please add Rocky Linux to list of supported distro's for dwm-titus as many of us open-source fanboys like rocky linux as it is super stable. Thanks.

**Comment by aASDa213ASD** [comment]
You might consider including some stacktrace next time, either way how in the world one supposed to know why exactly doesn't you dwm compiling :grey_question:
